[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
version = "0.1.0"
description = "Demo package for CI exercise"

[tool.setuptools]
py-modules = ["main"]   # <-- add this